.gitignore
.pre-commit-config.yaml
.pre-commit-hooks.yaml
CONTRIBUTING.md
Pipfile
Pipfile.lock
README.md
pyproject.toml
setup.cfg
src/commitlint/__init__.py
src/commitlint/cli.py
src/commitlint/commitlint.py

This is the 1st PR for commitlint, so it contains basic codes for commit message linting. The following have been through this PR:
- Added project structure and python project files.
- Added pre-commit config for this project
- Added pre-commit hooks for `commitlint`
- Added basic commit linting methods
- Added `commitlint` cli

Added commitlint code and pre-commit hooks and configs

---

src/commitlint/cli.py
src/commitlint/commitlint.py
src/commitlint/constants.py
src/commitlint/exceptions.py
src/commitlint/git_helpers.py
src/commitlint/messages.py
tests/test_cli.py
tests/test_commitlint/test_check_commit_message.py
tests/test_git_helpers.py

- Added support for commitlint with hash: `--hash`. 
- Added support for commitlint with hash range: `--from-hash` & `--to-hash`.
- Displayed multiple error messages
- Added exception handling and message display for commitlint errors (such as git errors).
- Added/Updated tests for above mentioned code.
- Minor fix on constants and messages variable names.
Fixes #6

feat: added support for hash, from-hash, and to-hash argument

---

.github/SECURITY.md
.github/workflows/test_action.yaml
CHANGELOG.md
README.md
setup.cfg

- Updated python package details
- Version bump to 0.2.0
N/A
-   [x] Other (please specify)
[Add any additional notes or context that you think the reviewers should know …

Package update and 0.2.0 version bump

---

.github/SECURITY.md
.github/workflows/test_action.yaml
CHANGELOG.md
README.md
action.yml
setup.cfg

- Updated Github Actions name.
- Updated readme docs for version info.
N/A
-   [x] Other (please specify)
N/A
By submitting this pull request, I confirm that I have read …

fix: updated github actions name and readme docs for version info

---

setup.cfg
src/commitlint/__init__.py
src/commitlint/__version__.py
src/commitlint/cli.py

Shows version information on `-V` and `--version`.
Fixes #13 
N/A
By submitting this pull request, I confirm that I have read and complied …

feat: show version info

---

setup.cfg

Updated project license information on setup.cfg
N/A
-   [x] Other (please specify)
-   [ ] ~~I have added/updated the necessary documentation on `README.md`.~~
-   [ ] ~~I have added appropriate test cases (if applicable) to ensure the changes are functioning correctly.~~
[Add any additional notes or context that you think the reviewers should know …

chore: updated license information

---

.github/workflows/test_action.yaml
README.md
action.yml
github_actions/run.py

The current GitHub Actions fail if `commitlint` throws an error. 
This pull request adds a new boolean parameter, fail_on_error, to GitHub Actions. This parameter will determine whether to fail the CI or proceed to the next step when `commitlint` throws an error. The default value for this parameter will be `true`.
The fail_on_error parameter is set to false when the user wants to ignore the commit message validation or handle the error in their own way.
Fixes #14 
-   [x] I have used [semantic …

feat: add fail_on_error parameter support on github actions

---

.github/workflows/test_action.yaml
README.md
github_actions/run.py

Added GitHub actions error message if commitlint fails.
Extra:
- Removed failed_on_error from the test_actions workflow.
- Updated docs for github actions
Fixes #24 
-   [x] Bug fix
-   [x] Enhancement
-   [ ] I have added appropriate test cases (if applicable) to ensure the changes …

feat: added error annotation on github actions

---

src/commitlint/cli.py
tests/test_cli.py

Added `--quiet` option in cli
Fixes: #15
-   [x] I have added appropriate test cases (if applicable) to ensure the changes are functioning correctly.
By submitting this pull request, I confirm that I have read and complied with the contribution …

feat(cli): added the quiet option in cli

---

tests/test_cli.py

In our tests, we are currently mocking `sys.exit`. Due to this mocking, the application logic does not exit immediately in the tests, resulting in many errors failing. Therefore, this issue is being addressed through this PR by removing the mock and checking for the `SystemExit` exception to be raised.
N/A
-   [x] Refactor
-   [x] Other (Tests)
-   [ ] I have …

test: refactor tests for system exit

---

.github/workflows/commitlint.yaml
README.md

This PR is for readiness for v1 release.
- Updated version information on docs and example actions.
- Refactored example usage syntax
- Renamed `test_action.yaml` to `commitlint.yaml` so user can take a reference as mentioned in the docs.
N/A
- …

docs: update usage information for v1

---

src/commitlint/cli.py
tests/test_cli.py

Give meaningful error message than giving the full stack trace when the file is not found.
Fixes: #44 
-   [x] Bug fix
-   [x] I have added appropriate test cases (if applicable) to ensure the changes are functioning correctly.
[Add any additional notes or …

fix: handle the file not found error gracefully

---

.github/workflows/release-please.yml
action.yml

- Updated immutable tag for commitlint actions
- Updated immutable hash for action workflows
N/A
-   [x] Other (security update)
[Add any additional notes or context …

fix: security updates on commitlint action and workflows

---

README.md

Modify README.md .
I noticed that the default value of **verbose** in GitHub Actions is different.
In the [actions.yml](https://github.com/opensource-nepal/commitlint/blob/main/action.yml#L8-L11) setting, the default value is false,
In README.md, it is described as true.
https://github.com/opensource-nepal/commitlint/blob/b98c73fb68f11b66ec8d3f227c6b129598c28726/action.yml#L8-L11
N/A
Examples: …

docs: update GitHub Actions Inputs section

---

src/commitlint/constants.py
tests/fixtures/linter.py

Allow Github dependabot bump commits.
Fixes #54
-   [x] I have added appropriate test cases (if applicable) to ensure the changes are functioning correctly.
[Add any additional notes or context that you think the reviewers should know about.]
By …

feat: allow bump commits

---

README.md
codecov.yml
src/commitlint/cli.py
src/commitlint/linter/_linter.py
src/commitlint/linter/utils.py
tests/fixtures/linter.py
tests/test_cli.py
tests/test_linter/test__linter.py
tests/test_linter/test_utils/test_remove_diff_from_commit_message.py

Handled commit message starting with '#'.
Comments are removed only on the file as a commit source (--file), as comments are only allowed through the file from git. This fix resolved the issue on GitHub Actions, CLI which uses hash values and direct commit messages.
For the file as a commit source, the linter will still remove the comments, including valid commits starting with '#'. A commit message starting with '#' will be treated as an empty commit. Since a commit starting with '#' does not follow the conventional commit specification, treating it as an empty commit yields the same result. Additionally, we display the full commit message in the input section, therefore the commit message will not be empty in this case.
Furthermore, the README document is updated mentioning not to use …

fix: handle commit message starting with #

---

.github/workflows/release-please.yml

Created major and minor tags on release for actions version.
Fixes #57 
-   [x] Other (CI)
[Add any additional notes or context that you think the reviewers should know …

ci: create major and minor tags on release for actions version

---

tests/test_cli.py

Refactor tests for CLI:
- Mocked `sys.args` instead of mocking `parse_args`.
N/A
-   [x] Refactor
-   [x] I have added appropriate test cases (if applicable) to ensure the changes are functioning correctly.
[Add any additional notes or context that you think the …

test: refactor tests for CLI

---

.github/workflows/release-please.yml
README.md

The annotated tag with a major version (e.g., v1) was created with a new timestamp. Therefore, pre-commit treated the major version tag as the latest tag.
Fix: 
- Created simple tags instead of annotated tags. Simple tags will reference the commit timestamp.
- Removed creation of minor version 2-digit tag.
Relates #64
-   [x] Bug fix …

fix: fix major version tag fetch on pre-commit autoupdate

---

Pipfile
github_actions/__main__.py
github_actions/action/run.py
pytest.ini
tests/fixtures/actions_env.py
tests/test_github_actions/test_event.py
tests/test_github_actions/test_run/test_check_commit_messages.py
tests/test_github_actions/test_run/test_get_pr_commit_messages.py
tests/test_github_actions/test_run/test_get_push_commit_messages.py
tests/test_github_actions/test_run/test_run.py
tests/test_github_actions/test_run/test_run_action.py
tests/test_github_actions/test_run/test_run_commitlint.py
tests/test_github_actions/test_utils/test_get_boolean_input.py
tests/test_github_actions/test_utils/test_get_input.py
tests/test_github_actions/test_utils/test_request_github_api.py
tests/test_github_actions/test_utils/test_write_line_to_file.py
tests/test_github_actions/test_utils/test_write_output.py
tests/test_linter/test_utils/test_is_ingored.py

- Added test for github actions with 100% coverage
[If your pull request is related to an existing issue, reference it here using the format "Fixes #issue_number".]
-   [x] Other (test)
-   [x] I have added appropriate test cases (if applicable) to ensure the changes are …

test: add tests for github actions with coverage

---

.gitignore
README.md
docs/cli.md
docs/conventional-commits.md

The purpose of these updates are to provide a quick reference for using Conventional Commits in CI and pre-commit.
- Update README.md (removed Conventional Commits details)
- Added additional docs for Conventional Commits and CLI
N/A
-   [ ] I …

docs: update README.md with additional docs

---

README.md

Add GitHub action permissions on README
Closes #71 
[Add any additional notes or context that you think the reviewers should know about.] …

docs: add github action permissions on README
